<template><view class="page-container"><view class="page-header"><text>我的</text></view><view class="content"><view v-if="!authStore.isLoggedIn" class="card"><text>请先登录</text><button class="btn btn-primary btn-block" @click="login">登录</button></view><view v-else><view class="card"><text class="name">{{ authStore.user?.nickname || '书友' }}</text><text>{{ authStore.user?.email }}</text></view><view class="card"><text class="title">创作统计</text><view class="stats"><text>作品 {{ stats.totalNovels }}</text><text>字数 {{ stats.totalWords }}</text><text>已完成 {{ stats.completedNovels }}</text></view></view><view class="card"><text class="title">模型配置</text><picker :value="routeIndex" :range="routeLabels" @change="changeRoute"><view class="input">{{ routeLabels[routeIndex] || '选择模型线路' }}</view></picker><button class="btn btn-primary btn-block" @click="saveModel">保存配置</button></view><button class="btn btn-outline btn-block" @click="logout">退出登录</button></view></view></view></template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { useAuthStore } from '../../stores/auth'
const authStore=useAuthStore(),stats=ref({totalNovels:0,totalWords:0,completedNovels:0}),routes=ref([]),routeId=ref('normal_1')
const routeLabels=computed(()=>routes.value.map(item=>item.alias||item.id));const routeIndex=computed(()=>Math.max(0,routes.value.findIndex(item=>item.id===routeId.value)))
onMounted(async()=>{if(!authStore.isLoggedIn)return;const [summary,config]=await Promise.all([authStore.getUserStats(),authStore.getModelConfig()]);stats.value=summary;routes.value=config.routes||[];routeId.value=config.modelConfig?.routeId||'normal_1'})
function changeRoute(e){routeId.value=routes.value[Number(e.detail.value)]?.id||routeId.value}async function saveModel(){await authStore.saveModelConfig({routeId:routeId.value})}function logout(){authStore.logout();uni.reLaunch({url:'/pages/login/login'})}function login(){uni.navigateTo({url:'/pages/login/login'})}
</script>
<style scoped>.page-container{padding-top:var(--header-height)}.page-header{position:fixed;top:0;left:0;right:0;height:var(--header-height);display:flex;align-items:center;justify-content:center;background:var(--card-bg);z-index:1}.content{padding:12px}.card{margin-bottom:12px;display:grid;gap:10px}.name,.title{font-weight:700}.stats{display:flex;justify-content:space-between;font-size:13px}.input{margin-top:6px}</style>
